In [1]:
import numpy as np
import pandas as pd

In [2]:
SVC_results = pd.read_csv('SVC-Results.csv')
LogReg_results = pd.read_csv('Logistic-Regression-Results.csv')
RandomForest_results = pd.read_csv('Random-Forest-Results.csv')

SVC best results

In [3]:
SVC_results.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 5 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Unnamed: 0              30 non-null     int64
 1   Team                    30 non-null     object
 2   predictions             30 non-null     int64
 3   prediction probability  30 non-null     float64
 4   Conf                    30 non-null     object
dtypes: float64(1), int64(2), object(2)
memory usage: 1.3+ KB

In [4]:
SVC_results = SVC_results.sort_values(['Conf','prediction probability'], ascending = False)

In [5]:
SVC_results.iloc[8:15,2] = 0
SVC_results.iloc[23:29,2] = 0

In [6]:
SVC_results

,Unnamed: 0,Team,predictions,prediction probability,Conf
29,14,Golden State Warriors,1,1.000000,West
20,5,Phoenix Suns,1,1.000000,West
16,1,Utah Jazz,1,0.985643,West
21,6,Dallas Mavericks,1,0.890659,West
22,7,Los Angeles Clippers,1,0.868424,West
28,13,Portland Trail Blazers,1,0.715284,West
23,8,Memphis Grizzlies,1,0.676011,West
27,12,Los Angeles Lakers,1,0.646166,West
19,4,Denver Nuggets,0,0.584961,West
25,10,Minnesota Timberwolves,0,0.396653,West
15,0,Sacramento Kings,0,0.035531,West
26,11,Oklahoma City Thunder,0,0.005905,West
24,9,San Antonio Spurs,0,0.001720,West
18,3,New Orleans Pelicans,0,0.000580,West
17,2,Houston Rockets,0,0.000014,West
11,11,Brooklyn Nets,1,1.000000,East
9,9,Miami Heat,1,0.999990,East
0,0,Chicago Bulls,1,0.996540,East
3,3,Washington Wizards,1,0.996281,East
13,13,Milwaukee Bucks,1,0.987168,East
14,14,Charlotte Hornets,1,0.981060,East
6,6,New York Knicks,1,0.937375,East
8,8,Boston Celtics,1,0.881454,East
5,5,Philadelphia 76ers,0,0.862537,East
12,12,Atlanta Hawks,0,0.816318,East
2,2,Cleveland Cavaliers,0,0.427048,East
4,4,Toronto Raptors,0,0.212694,East
7,7,Indiana Pacers,0,0.049706,East
10,10,Detroit Pistons,0,0.000015,East
1,1,Orlando Magic,0,0.000012,East

random forest best results

In [8]:
RandomForest_results.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 5 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Unnamed: 0              30 non-null     int64
 1   Team                    30 non-null     object
 2   predictions             30 non-null     int64
 3   prediction probability  30 non-null     float64
 4   Conf                    30 non-null     object
dtypes: float64(1), int64(2), object(2)
memory usage: 1.3+ KB

In [10]:
RandomForest_results = RandomForest_results.sort_values(['Conf','prediction probability'], ascending = False)

In [11]:
RandomForest_results.iloc[8:15,2] = 0
RandomForest_results.iloc[23:29,2] = 0

In [12]:
RandomForest_results

,Unnamed: 0,Team,predictions,prediction probability,Conf
20,5,Phoenix Suns,1,0.979040,West
16,1,Utah Jazz,1,0.951586,West
29,14,Golden State Warriors,1,0.936667,West
21,6,Dallas Mavericks,1,0.783607,West
22,7,Los Angeles Clippers,1,0.767407,West
28,13,Portland Trail Blazers,1,0.726201,West
23,8,Memphis Grizzlies,1,0.690869,West
27,12,Los Angeles Lakers,1,0.648654,West
19,4,Denver Nuggets,0,0.595147,West
25,10,Minnesota Timberwolves,0,0.464882,West
24,9,San Antonio Spurs,0,0.411515,West
15,0,Sacramento Kings,0,0.135367,West
26,11,Oklahoma City Thunder,0,0.111549,West
17,2,Houston Rockets,0,0.106882,West
18,3,New Orleans Pelicans,0,0.042085,West
5,5,Philadelphia 76ers,1,0.957222,East
3,3,Washington Wizards,1,0.952416,East
13,13,Milwaukee Bucks,1,0.934442,East
8,8,Boston Celtics,1,0.925359,East
9,9,Miami Heat,1,0.883915,East
0,0,Chicago Bulls,1,0.880192,East
12,12,Atlanta Hawks,1,0.878946,East
14,14,Charlotte Hornets,1,0.866970,East
11,11,Brooklyn Nets,0,0.828180,East
6,6,New York Knicks,0,0.800701,East
2,2,Cleveland Cavaliers,0,0.523712,East
4,4,Toronto Raptors,0,0.441443,East
7,7,Indiana Pacers,0,0.248902,East
1,1,Orlando Magic,0,0.081640,East
10,10,Detroit Pistons,0,0.048379,East

logistic regression best results

In [13]:
LogReg_results.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 5 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Unnamed: 0              30 non-null     int64
 1   Team                    30 non-null     object
 2   predictions             30 non-null     int64
 3   prediction probability  30 non-null     float64
 4   Conf                    30 non-null     object
dtypes: float64(1), int64(2), object(2)
memory usage: 1.3+ KB

In [14]:
LogReg_results = LogReg_results.sort_values(['Conf','prediction probability'], ascending = False)

In [15]:
LogReg_results.iloc[8:15,2] = 0
LogReg_results.iloc[23:29,2] = 0

In [16]:
LogReg_results

,Unnamed: 0,Team,predictions,prediction probability,Conf
29,14,Golden State Warriors,1,0.999944,West
20,5,Phoenix Suns,1,0.999798,West
16,1,Utah Jazz,1,0.984719,West
21,6,Dallas Mavericks,1,0.942490,West
22,7,Los Angeles Clippers,1,0.824967,West
28,13,Portland Trail Blazers,1,0.747283,West
19,4,Denver Nuggets,1,0.729345,West
23,8,Memphis Grizzlies,1,0.697896,West
25,10,Minnesota Timberwolves,0,0.663054,West
27,12,Los Angeles Lakers,0,0.503502,West
15,0,Sacramento Kings,0,0.051116,West
26,11,Oklahoma City Thunder,0,0.021237,West
24,9,San Antonio Spurs,0,0.011289,West
18,3,New Orleans Pelicans,0,0.001089,West
17,2,Houston Rockets,0,0.000186,West
11,11,Brooklyn Nets,1,0.999683,East
9,9,Miami Heat,1,0.997065,East
3,3,Washington Wizards,1,0.994121,East
0,0,Chicago Bulls,1,0.991051,East
13,13,Milwaukee Bucks,1,0.942429,East
8,8,Boston Celtics,1,0.936757,East
6,6,New York Knicks,1,0.907048,East
14,14,Charlotte Hornets,1,0.893661,East
5,5,Philadelphia 76ers,0,0.819328,East
12,12,Atlanta Hawks,0,0.774137,East
2,2,Cleveland Cavaliers,0,0.455174,East
4,4,Toronto Raptors,0,0.427932,East
7,7,Indiana Pacers,0,0.063009,East
10,10,Detroit Pistons,0,0.000404,East
1,1,Orlando Magic,0,0.000066,East